### ISSUE TITLE
API features prevents support to collections of other types in a single service.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/OGC-API-Hackathon-2019#37]
In its current wording, OGC API features forces all collections to be downloadable through "items". Read the issue here:
https://github.com/opengeospatial/WFS_FES/issues/249

Having the possibility that a collection cannot be downloadable as features was something that some people expressed as needed in the hackathon, I believe it is worth to mention here.

**Comment by ghobona** [comment]
Closing this issue because it is under discussion in the OGC API - Common repo.
